workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: betaImage

ingress:
  main:
    enabled: true
    hosts:
      - host: vault.example.com
        paths:
          - path: /
            pathType: Prefix
